### ISSUE TITLE
Use 'latest' github release API instead?

### ISSUE THREAD

**Issue by matthewgonzalez** [axelrindle/github-version-checker#1]
First off thanks for this little module.

Wanted to know why the complete release JSON is being pulled rather than just using the 'latest' URI? Is it because it doesn't include the prereleases?

ie. /repos/:owner/:repo/releases/latest

https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by axelrindle** [comment]
@matthewgonzalez Yes, you are right. I wanted to include prereleases into the version check. But thanks for asking, I will think of some changes ASAP.

**Comment by matthewgonzalez** [comment]
Ok thanks for the response.

I was just noticing that the JSON returned from the 'release' URI can be substantially larger. An example:

https://api.github.com/repos/atom/atom/releases `1MB`
https://api.github.com/repos/atom/atom/releases/latest `27kb`

Granted, not many projects will have a release list as heavy as Atom... In my case, I'm more interested in just grabbing the latest version (w/out prereleases), so having a method to call or option to set for that would be nice.

Thanks again.

**Comment by ztalbot2000** [comment]
ReferenceError: version is not defined
    at IncomingMessage.res.on (/usr/local/lib/node_modules/github-version-checker/lib/check.js:81:24)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1142:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[6/14/2019, 6:08:54 PM] Got SIGTERM, shutting down Homebridge...
^CZarfs-Mac-mini:~ zarf$ node -v
v11.13.0

From debugging, found = true, but since version is defined as a let within the for scope, it is undefined outside causing the reference error.

I was able to fix this by defining version ahead of the for loop.  Here is my diff

72a73
>       let version;
74c75
<         let version = json[i];
---
>         version = json[i];

John Talbot
